FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install

ENV DATABASE_USERNAME NULL
ENV DATABASE_PASSWORD NULL
ENV DATABASE_DATABASE_NAME NULL
ENV DATABASE_LOGGING NULL
ENV DATABASE_HOST NULL



COPY . .
EXPOSE 3000
CMD [ "node", "index.js" ]
