version: '3.8'


services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=bosta_db
      - MYSQL_USER=bosta_app
      - MYSQL_PASSWORD=bosta_app
    expose:
      - 3306
  web:
    build: .
    # restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_USERNAME=bosta_app
      - DATABASE_PASSWORD=bosta_app
      - DATABASE_DATABASE_NAME=bosta_db
      - DATABASE_HOST=mysql
      
      - BASE_LINK=http://adhamnourmainpc:3000
    depends_on:
      - mysql